# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('cc_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('issuer', models.CharField(default='x', max_length=100)),
                ('card', models.CharField(default='x', max_length=100)),
                ('date_approved', models.DateField()),
                ('bonus_recieved', models.DateField()),
                ('bonus', models.IntegerField(default=0)),
                ('min_spend', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('line', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('issue_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.CreditCard')),
            ],
        ),
        migrations.CreateModel(
            name='TravelStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('traveling_with', models.CharField(max_length=100)),
                ('wake_time', models.TimeField()),
                ('sleep_time', models.TimeField()),
                ('naps', models.IntegerField(default=0)),
                ('breakfast_time', models.TimeField()),
                ('breakfast_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breakfast_type', models.CharField(max_length=100)),
                ('lunch_time', models.TimeField()),
                ('lunch_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lunch_type', models.CharField(max_length=100)),
                ('dinner_time', models.TimeField()),
                ('dinner_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dinner_type', models.CharField(max_length=100)),
                ('glasses_of_wine', models.IntegerField(default=0)),
                ('wine_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cocktail_count', models.IntegerField(default=0)),
                ('cocktail_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('miles_air', models.IntegerField(default=0)),
                ('miles_train', models.IntegerField(default=0)),
                ('miles_car', models.IntegerField(default=0)),
                ('miles_bus', models.IntegerField(default=0)),
                ('miles_walk', models.IntegerField(default=0)),
                ('housing_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('housing_name', models.CharField(max_length=100)),
                ('housing_type', models.CharField(max_length=100)),
                ('num_sex', models.IntegerField(default=0)),
                ('num_master', models.IntegerField(default=0)),
                ('num_poops', models.IntegerField(default=0)),
                ('hours_read', models.DecimalField(decimal_places=2, max_digits=5)),
                ('book', models.CharField(max_length=100)),
                ('hours_tv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('show', models.CharField(max_length=100)),
                ('hours_podcast', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('podcast', models.CharField(default='', max_length=100)),
                ('hours_music', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('museums_visited', models.IntegerField(default=0)),
                ('friends_met', models.IntegerField(default=0)),
                ('tour_name', models.CharField(default='', max_length=100)),
                ('tour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('num_pictures_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='x', max_length=100)),
                ('email', models.CharField(default='x', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='issued',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.User'),
        ),
    ]
