# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelstats',
            name='miles_walk',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
