# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buy_Date', models.DateField()),
                ('Sell_Date', models.DateField()),
                ('Symbol', models.CharField(default='x', max_length=6)),
                ('Quanity', models.IntegerField(default=0)),
                ('Cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Symbol', models.CharField(default='x', max_length=6)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
