# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystocks',
            name='Sell_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
