# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180202_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystocks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
