# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20180202_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystocks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
