# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180202_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mystocks',
            old_name='Cost',
            new_name='Buy_Price',
        ),
        migrations.AddField(
            model_name='mystocks',
            name='Sell_Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
