# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Word_List',
            new_name='Occurance_Dict',
        ),
        migrations.AddField(
            model_name='books',
            name='Average_Unique_Word_Length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='Sentence_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='Unique_Word_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='Word_Per_Sentence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='Unique_Words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='Vocab_Density',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='Word_Count',
            field=models.IntegerField(default=0),
        ),
    ]
