# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170222_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Average_Unique_Word_Length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='Word_Per_Sentence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
