# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170222_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Title',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
