# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Cat', models.CharField(max_length=1000)),
                ('Name', models.CharField(default='', max_length=1000)),
                ('Weight', models.IntegerField()),
            ],
        ),
    ]
