# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0002_winners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=1000)),
                ('Selections', picklefield.fields.PickledObjectField(default=[], editable=False)),
            ],
        ),
    ]
