# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Year',
            field=models.IntegerField(default=0),
        ),
    ]
