# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0004_users_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Cat',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='Selections',
            field=models.CharField(max_length=1000),
        ),
    ]
