# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar', '0005_auto_20180303_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Selections',
            new_name='Favorite',
        ),
        migrations.AddField(
            model_name='users',
            name='Won',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
