# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Reps', models.IntegerField(default=0)),
                ('Weight', models.IntegerField(default=0)),
                ('Type', models.CharField(default='x', max_length=100)),
                ('Exercise', models.CharField(default='x', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='x', max_length=100)),
                ('Exercise', models.CharField(default='x', max_length=100)),
            ],
        ),
    ]
