# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, unique=True)),
                ('type', models.CharField(max_length=25)),
                ('definition', models.CharField(max_length=1000)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
