# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('population', models.IntegerField()),
                ('color', models.CharField(max_length=1000)),
                ('type', models.CharField(default='Type 1', max_length=100)),
                ('connectionCities', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('lat', models.FloatField(default=-1)),
                ('long', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyEventCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rules', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=5000)),
                ('type', models.CharField(default='Type 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EpidemicCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('type', models.CharField(default='Type 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameId', models.IntegerField(unique=True)),
                ('gameStarted', models.BooleanField(default=False)),
                ('users', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('infectionCards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('infectionDiscards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('actionCards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('actionDiscards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('rollCards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('blueTokens', models.IntegerField(default='x')),
                ('blackTokens', models.IntegerField(default='x')),
                ('redTokens', models.IntegerField(default='x')),
                ('yellowTokens', models.IntegerField(default='x')),
                ('purpleTokens', models.IntegerField(default='x')),
                ('infectionRate', models.IntegerField(default='x')),
                ('outbreaks', models.IntegerField(default='x')),
                ('blueCure', models.BooleanField(default=False)),
                ('blackCure', models.BooleanField(default=False)),
                ('redCure', models.BooleanField(default=False)),
                ('yellowCure', models.BooleanField(default=False)),
                ('purpleCure', models.BooleanField(default=False)),
                ('mapInfection', picklefield.fields.PickledObjectField(default=[], editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='InfectionCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('color', models.CharField(max_length=1000)),
                ('type', models.CharField(default='Type 2', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MutationCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rules', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=5000)),
                ('type', models.CharField(default='Type 1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField(unique=True)),
                ('playerName', models.CharField(default='x', max_length=1000)),
                ('playerCards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('rollCards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('color', models.CharField(default='x', max_length=1000)),
                ('currentLocation', models.CharField(default='Atlanta', max_length=1000)),
                ('notes', models.CharField(default='Personal Notes-', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RolesCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('color', models.CharField(max_length=100)),
                ('type', models.CharField(default='Type 3', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.IntegerField(unique=True)),
                ('createdBy', models.CharField(default='x', max_length=1000)),
                ('numberOfPandemicCards', models.IntegerField()),
                ('numberOfRoleCards', models.IntegerField()),
                ('mutation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialEventCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('rules', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=5000)),
                ('type', models.CharField(default='Type 1', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Room'),
        ),
        migrations.AddField(
            model_name='game',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Room'),
        ),
    ]
