# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='createdBy',
            field=models.CharField(default='x', max_length=1000),
        ),
    ]
