# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='blackTokens',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='game',
            name='blueTokens',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='game',
            name='infectionRate',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='game',
            name='outbreaks',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='game',
            name='purpleTokens',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='game',
            name='redTokens',
            field=models.IntegerField(default='x'),
        ),
        migrations.AlterField(
            model_name='game',
            name='users',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='yellowTokens',
            field=models.IntegerField(default='x'),
        ),
    ]
