# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170412_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField(unique=True)),
                ('playerCards', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('roleCard', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('color', models.CharField(default='x', max_length=1000)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Room')),
            ],
        ),
    ]
