# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playerName',
            field=models.CharField(default='x', max_length=1000),
        ),
    ]
