# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_playername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gameId',
        ),
    ]
