# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_player_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Room', unique=True),
        ),
    ]
