# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170412_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentLocation',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='notes',
            field=models.CharField(default='x', max_length=1000),
        ),
    ]
