# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 05:41
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170413_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rollCards',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
