# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_rollcards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='roleCard',
            new_name='rollCards',
        ),
    ]
