# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20170413_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='notes',
            field=models.CharField(default='Personal Notes-', max_length=1000),
        ),
    ]
