# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20170414_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycards',
            name='lat',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='citycards',
            name='long',
            field=models.FloatField(default=-1),
        ),
    ]
