# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 07:33
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170414_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mapInfection',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
