# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_mapinfection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentLocation',
            field=models.CharField(default='Atlanta', max_length=1000),
        ),
    ]
