# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=100)),
                ('games', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('so', models.IntegerField()),
                ('hidp', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('dbo', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('h', models.IntegerField()),
                ('firstb', models.IntegerField()),
                ('secondb', models.IntegerField()),
                ('thirdb', models.IntegerField()),
                ('fourthb', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('r', models.IntegerField()),
                ('rbi', models.IntegerField()),
            ],
        ),
    ]
