# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='avg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='stats',
            name='obp',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='stats',
            name='ops',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='stats',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='slg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='stats',
            name='tb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ab',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='bb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='dbo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='firstb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='fourthb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='hidp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='pa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='player',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='r',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rbi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='sb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='season',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='secondb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='so',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='thirdb',
            field=models.IntegerField(default=0),
        ),
    ]
