# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softball', '0004_auto_20170227_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='obp',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='ops',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='slg',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tb',
        ),
    ]
