# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softball', '0006_polls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polls',
        ),
    ]
