class config():
    my_character_dict = {
        'Oakley':{
            'exp': 340,
            'color': '#ff5f5f',
            'class':'Druid',
            'race':'Human',
            'level': '2',
            'background': 'Outlander',
            'alignment': 'CG',
            'hp': '12',
            'hit_die': 'd8',
            'ac': '15',
            'speed': '30',
            'prof_bonus': '+2',
            'passive_perception': '14',
            'stats': [14,14,18,16,18,12],
            'saving_throw': "Intelligence and Wisdom",
            'proficiencies': "Athletics, Survival",
            'armor': "Leather Armor (11) <br> Wood Shield (+2)",
            'weapon': "Scimitar +4 1d8+2",
            'spells': "Spell Save: 14, Wisdom, +6",
            'cantrip': "Poison Spray <br> Guidence",
            'level_1': "Cure Wounds <br> Thunder Wave",
        },
        'Tarlos Borevain': {
            'exp': 340,
            'color': '#ff5fff',
            'class': 'Rogue',
            'race': 'Halfling (GW)',
            'level': '2',
            'background': 'Outlander',
            'alignment': 'CN',
            'hp': '11',
            'hit_die': 'd8',
            'ac': '16',
            'speed': '25',
            'prof_bonus': '2',
            'passive_perception': '11',
            'stats': [11,20,16,12,13,11],
            'saving_throw': "Dexterity, Intelligence",
            'proficiencies': "Acrobatics, Athletics, Insight, Sleight of Hand, Stealth, Survival",
            'armor': "Leather Armor (11)",
            'weapon': "Rapier +7 1d8+5 <br> Shortbow +7 1d6+5",
            'spells': "None",
            'cantrip': "None",
            'level_1': "None",
        },
        'Val': {
            'exp': 340,
            'color': '#5fff5f',
            'class': 'Warlock',
            'race': 'Tiefling',
            'level': '2',
            'background': 'Criminal',
            'alignment': 'CN',
            'hp': '6',
            'hit_die': 'd8',
            'ac': '13',
            'speed': '30',
            'prof_bonus': '2',
            'passive_perception': '12',
            'stats': [8, 15, 7, 10, 15, 16],
            'saving_throw': "Wisdom, Charisma",
            'proficiencies': "Arcana, Deception, Intimidation, Stealth",
            'armor': "Leather Armor (11)",
            'weapon': "Sickle +4 1d8+2 <br> Crossbow +4 1d4+2",
            'spells': "Spell Save: 13, Charisma, +5",
            'cantrip': "Minor Illusion <br> Eldritch Blast",
            'level_1': "Witch Bolt",
        },
        'Dracodea': {
            'exp': 340,
            'color': '#5fffff',
            'class': 'Paladin',
            'race': 'Dragonborn',
            'level': '2',
            'background': 'Soldier',
            'alignment': 'CN',
            'hp': '11',
            'hit_die': 'd10',
            'ac': '15',
            'speed': '30',
            'prof_bonus': '2',
            'passive_perception': '10',
            'stats': [17, 11, 13, 8, 11, 17],
            'saving_throw': "Wisdom, Charisma",
            'proficiencies': "Athletics, Intimidation, Medicine, Persuasion",
            'armor': "Chain Shirt (13) <br> Shield (+2)",
            'weapon': "Warhammer +5 1d8+3 <br> Javalins +2 1d6+0",
            'spells': "Spell Save: 13, Charisma, +5",
            'cantrip': "None",
            'level_1': "None",
        }

    }
