# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameId', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('gameDeck', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerId', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('playerName', models.CharField(default='random_name', max_length=20)),
                ('cards', models.CharField(default='x', max_length=10)),
                ('score', models.IntegerField(max_length=6)),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loveletter.Game')),
            ],
        ),
    ]
