# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(),
        ),
    ]
