# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveletter', '0002_auto_20170323_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playerOrder',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
