# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveletter', '0003_game_playerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameStarted',
            field=models.BooleanField(default=False),
        ),
    ]
