# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell', models.CharField(default='x', max_length=100)),
                ('spell_type', models.CharField(default='x', max_length=100)),
                ('casting_time', models.CharField(default='x', max_length=100)),
                ('range', models.CharField(default='x', max_length=100)),
                ('components', models.CharField(default='x', max_length=100)),
                ('duration', models.CharField(default='x', max_length=100)),
                ('description', models.CharField(default='x', max_length=100000)),
                ('whose_spell', models.CharField(default='x', max_length=100)),
                ('page', models.CharField(default='x', max_length=100)),
            ],
        ),
    ]
