# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-26 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='x', max_length=100)),
                ('color', models.CharField(default='x', max_length=100)),
                ('char_class', models.CharField(default='x', max_length=100)),
                ('race', models.CharField(default='x', max_length=100)),
                ('level', models.CharField(default='x', max_length=100)),
                ('background', models.CharField(default='x', max_length=100)),
                ('alignment', models.CharField(default='x', max_length=100)),
                ('hp', models.CharField(default='x', max_length=100)),
                ('ac', models.CharField(default='x', max_length=100)),
                ('speed', models.CharField(default='x', max_length=100)),
                ('Sentence_Count', models.IntegerField(default=0)),
                ('Word_Per_Sentence', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Unique_Words', models.IntegerField(default=0)),
                ('Average_Unique_Word_Length', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Vocab_Density', models.FloatField(default=0)),
                ('Unique_Word_list', models.TextField(null=True)),
                ('Occurance_Dict', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='spells',
            name='level',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
