# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_auto_20180726_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='Average_Unique_Word_Length',
        ),
        migrations.RemoveField(
            model_name='character',
            name='Occurance_Dict',
        ),
        migrations.RemoveField(
            model_name='character',
            name='Sentence_Count',
        ),
        migrations.RemoveField(
            model_name='character',
            name='Unique_Word_list',
        ),
        migrations.RemoveField(
            model_name='character',
            name='Unique_Words',
        ),
        migrations.RemoveField(
            model_name='character',
            name='Vocab_Density',
        ),
        migrations.RemoveField(
            model_name='character',
            name='Word_Per_Sentence',
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='cantrip',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='con_ability',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='dex_ability',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='hit_die',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='int_ability',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='level_1',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_2',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_3',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_4',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_5',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_6',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_7',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_8',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='level_9',
            field=models.CharField(default='x', max_length=1000),
        ),
        migrations.AddField(
            model_name='character',
            name='other',
            field=models.CharField(default='x', max_length=10000),
        ),
        migrations.AddField(
            model_name='character',
            name='passive_perception',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='prof_bonus',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throw',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='str_ability',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='wis_ability',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
