# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20180822_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='char_ability',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
