# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_character_char_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='x', max_length=100)),
                ('color', models.CharField(default='x', max_length=100)),
                ('experience', models.CharField(default='x', max_length=100)),
                ('char_class', models.CharField(default='x', max_length=100)),
                ('race', models.CharField(default='x', max_length=100)),
                ('level', models.CharField(default='x', max_length=100)),
                ('background', models.CharField(default='x', max_length=100)),
                ('alignment', models.CharField(default='x', max_length=100)),
                ('hp', models.CharField(default='x', max_length=100)),
                ('hit_die', models.CharField(default='x', max_length=100)),
                ('ac', models.CharField(default='x', max_length=100)),
                ('speed', models.CharField(default='x', max_length=100)),
                ('prof_bonus', models.CharField(default='x', max_length=100)),
                ('passive_perception', models.CharField(default='x', max_length=100)),
                ('str_ability', models.CharField(default='x', max_length=100)),
                ('dex_ability', models.CharField(default='x', max_length=100)),
                ('con_ability', models.CharField(default='x', max_length=100)),
                ('int_ability', models.CharField(default='x', max_length=100)),
                ('wis_ability', models.CharField(default='x', max_length=100)),
                ('char_ability', models.CharField(default='x', max_length=100)),
                ('saving_throw', models.CharField(default='x', max_length=100)),
                ('proficiencies', models.CharField(default='x', max_length=100)),
                ('armor', models.CharField(default='x', max_length=100)),
                ('weapon', models.CharField(default='x', max_length=100)),
                ('spells', models.CharField(default='x', max_length=100)),
                ('cantrip', models.CharField(default='x', max_length=1000)),
                ('level_1', models.CharField(default='x', max_length=1000)),
                ('level_2', models.CharField(default='x', max_length=1000)),
                ('level_3', models.CharField(default='x', max_length=1000)),
                ('level_4', models.CharField(default='x', max_length=1000)),
                ('level_5', models.CharField(default='x', max_length=1000)),
                ('level_6', models.CharField(default='x', max_length=1000)),
                ('level_7', models.CharField(default='x', max_length=1000)),
                ('level_8', models.CharField(default='x', max_length=1000)),
                ('level_9', models.CharField(default='x', max_length=1000)),
                ('other', models.CharField(default='x', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
