# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0006_auto_20180922_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='xp',
            field=models.CharField(default='x', max_length=10000),
        ),
    ]
